name: Adjust Star Counts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  my_first_job:
    steps:
      - name: Check Commit Message
      run: echo ${{ github.event.commits[0].message }}.